version: '3'
services:
  db_odoo_cv:
    image: postgres:15
    volumes:
      - odoo_pg_data_retana:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    restart: always
    container_name: db_odoo_cv

  odoo_cv:
    image: odoo:17
    depends_on:
      - db_odoo_cv
    ports:
      - "8888:8069"
    volumes:
      - odoo_data_retana:/var/lib/odoo
      - ./extra-addons:/mnt/extra-addons
      - ./config/local.conf:/etc/odoo/odoo.conf
      - ./odoo-filestore:/var/lib/odoo/.local/share/Odoo/filestore
    environment:
      - HOST=db_odoo_cv
      - USER=odoo
      - PASSWORD=odoo
    restart: always
    container_name: odoo_cv
    user: "root"
    command: bash -c "pip install --no-cache-dir -r /mnt/extra-addons/requirements.txt && /usr/bin/odoo -c /etc/odoo/odoo.conf --dev all"

volumes:
  odoo_pg_data_retana:
  odoo_data_retana:
  odoo_filestore: